version: '3'

volumes:
    data: {}

services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=apt
        ports:
            - 3306:3306
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
            - --default-authentication-plugin=mysql_native_password
        volumes:
            - ./data:/var/lib/mysql
    api:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        volumes:
            - .:/app/
        environment:
            - DB_NAME=apt
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_HOST=db
            - DB_PORT=3306
            - SECRET_KEY=SECRET_KEY
            - ALGORITHM=HS256
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - db
        command: >-
            sh -c 'python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000'