# Generated by Django 3.2.4 on 2021-07-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='password',
        ),
    ]
